#=======================================================================================================================
#
#           MK-OPManager Plugin Configuration.
#                             插件配置
#                                                                   Author: Mark_Chanel
#                                                                    作者
#
#         请注意! 您在该文件上的任何错误操作都可能导致插件的运行错误! 对于由此原因造成的不可控后果请自行承担!
#               (错误操作包括但不限于: 不遵照YAML语言标准写入设置,写入非法的设定值,写入一些超出插件功能的设置)
#
#         Please Attention!
#               If you want to change the contents of this file, you need to know the YAML language syntax and enter the values correctly .
#               Any incorrect changes you make to this file could cause the plug-in to run abnormally.
#
#=======================================================================================================================
General:

  # 密码
  # 请注意! 该选项是本插件所有主要操作的必须要素.
  # 无密码格式限制,但不可为空!
  # 第一次启动建议更改该选项!
  Password: Mark_Chanel_Password

  # 检查间隔.
  # 插件会定时检查玩家中有无未被标记的 OP 并撤回 OP 身份.
  # 该选项即定义这一过程执行完毕后的间隔时间.
  # 单位: 秒
  CheckInterval: 1

# 设置自定义语言.
Messages:

  # 当玩家试图使用已被禁止的命令时的回复语.
  CommandDenied: "&c你没有权限执行此命令!"

  # 当玩家试图使用 /op 命令时的回复语.
  OPDenied: "&c你未拥有超级管理员身份. &c操作被拒绝."

  # 当某一玩家为 OP 身份且未被标记,被检测时的回复语.
  OPCheckDenied: "&c你未拥有管理员或临时管理员身份. &c已强行取消OP."

  # 当临时管理员身份到期时的回复语.
  OPTimeOut: "&a你的临时管理员身份已到期. &a你已不再是管理员."

