#=======================================================================================================================
#
#           MK-OPManager Plugin Configuration.
#                             插件配置
#                                         Author: Mark_Chanel
#                                          作者
#
#         请注意! 您在该文件上的任何错误操作都可能导致插件的运行错误! 对于由此原因造成的不可控后果请自行承担!
#               (错误操作包括但不限于: 不遵照YAML语言标准写入设置,写入非法的设定值,写入一些超出插件功能的设置)
#
#         Please Attention!
#               If you want to change the contents of this file, you need to know the YAML language syntax.
#               Any incorrect changes you make to this file could cause the plug-in to run abnormally.
#
#=======================================================================================================================

# 密码
# 请注意! 该选项是本插件所有主要操作的必须要素.
# 无密码格式限制,但不可为空!
# 第一次启动建议更改该选项!
Password: Mark_Chanel_Password

# 超级管理员
# 在该选项中列出的玩家会得到与 原OP 同等权利.
# 格式: 玩家名
SuperAdministrators:
#  - Mark_Chanel

# 管理员
# 在该选项中列出的玩家会有 OP 身份,但权利可能低于超级管理员,这取决于 BannedCommands 中列出的 OP 限制命令.
OPs:
#  - Mark_Chanel

# 临时管理员
# 权利与管理员相同,但有身份限制,这取决于 /addTempOP 命令中指定的时间.
# 但是该选项仅仅用于标记,不建议修改该选项.
TempOPs:
#  - Mark_Chanel

# 禁止命令
# 该选项用于禁止某些命令.
# 在该选项下的命令仅超级管理员可使用.
# 尽可能的以小写输入
BannedCommands:
  - nuke

# 检查间隔
# 插件会定时检查玩家中有无未被标记的 OP 并撤回 OP 身份.
# 该选项即定义这一过程执行完毕后的间隔时间
# 单位: 秒
CheckInterval: 1

# 语言自定义设置
Messages:
  # 玩家输入了被禁止的命令时的回复语.
  CommandDenied: "&c你没有权限执行此命令!"

  # 玩家在未被标记的情况下使用 /OP 的回复语.
  OPDenied: "&c你不在白名单中! &c操作被拒绝!"