name: MK-OPManager
main: me.markchanel.plugin.MK.OPManager.MKOPManager
version: 1.0.BETA.251
api-version: 1.13
author: Mark_Chanel
website: https://gitee.com/markchanel/mk-opmanager
commands:
  mkopmanager:
    description: Main Command.
    usage: /mkopmanager
    aliases:
      - mkom

permissions:
  mkopmanager.help:
    default: false
  mkopmanager.addOP:
    default: false
  mkopmanager.addTempOP:
    default: false
  mkopmanager.addCommands:
    default: false
