settings:
  SuperAdministrators: []
  WhiteList: []
  TempWhiteList: []
  BannedCommands:
    - nuke

Messages:
  CommandDenied: "&c你没有权限执行此命令!"
  OPDenied: "&c你未拥有超级管理员身份. &c操作被拒绝."
  OPCheckDenied: "&c你未拥有管理员或临时管理员身份. &c已强行取消OP."
  OPTimeOut: "&a你的临时管理员身份已到期. &a你已不再是管理员."