#------------------------------------------------------------------------------
name: MK-OPManager
main: me.markchanel.plugin.MK.OPManager.Main
version: 1.1.0.Beta2
#------------------------------------------------------------------------------
api-version: 1.13
author: ManGo_MilkTea
website: https://gitee.com/ManGo_MilkTea/MK-OPManager
softdepend: [Essentials]
commands:
  mkopmanager:
    description: Main Command.
    usage: /mkopmanager
    aliases: [mkom]

permissions:
  mkopmanager.admin:
    default: false

